name: pancake-go-build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v ./...

    - name: Get version number
      run: |
        version_output=$(./pancake version)
        version=${version_output#Pancake }
        version=$(echo "$version" | xargs)
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Tag release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git tag -a $VERSION -m "Releasing Pancake version $VERSION"
        git push origin $VERSION
